{{- if not .Values.core.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "core.claimName" . }}
{{- if .Values.core.persistence.annotations }}
  annotations:
{{ toYaml .Values.core.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.core.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.core.persistence.size }}
  {{- if .Values.core.persistence.storageClass }}
  {{- if (eq "-" .Values.core.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.core.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if not .Values.web.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "web.claimName" . }}
{{- if .Values.web.persistence.annotations }}
  annotations:
{{ toYaml .Values.web.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.web.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.web.persistence.size }}
  {{- if .Values.web.persistence.storageClass }}
  {{- if (eq "-" .Values.web.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.web.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
